export const projects = [
  {
    id: "1",
    image: "/wild.jpg",
    imageDetailed: "/project1Detailed.png",
    title: "Wild Oasis - Hospitality",
    detailedtitle: "👉 Wild Oasis - Hospitality",
    description:
      " A platform for booking cabins with intuitive navigation and modern design.",
    Detaileddescription:
      "For this project, I worked on the design and development of Saibernext’s SaaS platform. The goal was to create a website that embodies the slogan 'Design that makes an impact, effortlessly.' I focused on building a user-friendly, modern interface that showcases the company’s tools in a clean and intuitive way.",
    link: "https://wild-oasis-luxury.vercel.app/",
    industry1: "Industry",
    industryDesc1: "Hospitality",
    service1: "Service",
    serviceDesc1: "Room/Accommodation",
    tools1: "Tools",
    tools1Desc: "Next.js, Tailwind CSS, Supabase, NextAuth.js",
    complete1: "Completion Timeline",
    complete1Desc: "1 Week",
    started: "How It All Began",
    startedDesc:
      "I began the Wild Oasis project by taking a Udemy course focused on building websites with Next.js and Supabase. As a beginner in web development, I was excited to dive into these tools, as they offered powerful features for creating dynamic, full-stack web applications. Next.js helped me quickly set up a server-side rendered site with efficient routing, while Supabase provided an easy-to-use backend for authentication and database management. The course guided me through setting up a reservation system and integrating these technologies, allowing me to focus on building a functional, user-friendly website. This project was a great learning experience, and it helped me apply and improve my skills in both front-end and back-end development.",
    process: "Project Process",
    processDesc:
      "I started the Wild Oasis website by following a Udemy course where I learned Next.js for the front-end and Supabase for the back-end. After setting up the project and configuring Next.js with server-side rendering, I focused on the design using Tailwind CSS for responsiveness. I integrated Supabase for user authentication and reservation data storage. Then, I developed features like cabin booking and calendar functionality. After testing and final adjustments, I deployed the website on Vercel, ensuring smooth user experience and real-time updates. This project allowed me to apply React, Next.js, and Supabase skills in building a real-world web application.",
    github: "https://github.com/SabaGG71/wild-oasis",
    alt: "Wild Oasis",
  },
  {
    id: "2",
    image: "/project3.jpg",
    imageDetailed: "/project3Detailed.png",
    title: "SaiberNext - SaaS",
    detailedtitle: "👩‍💻 SaiberNext - SaaS",
    description:
      "A modern SaaS platform that simplifies business operations with powerful tools and an intuitive interface.",
    link: "https://saibernext.vercel.app/",
    Detaileddescription:
      "A modern SaaS platform designed to streamline business operations with powerful, integrated tools and an intuitive user interface. This platform enables businesses of all sizes to efficiently manage their workflows, automate repetitive tasks, and analyze key data in real-time. With features such as customizable dashboards, detailed analytics, and collaboration tools, users can easily track performance, improve productivity, and enhance decision-making.",
    industry1: "Industry",
    industryDesc1: "SAAS",
    service1: "Service",
    serviceDesc1: "Design",
    tools1: "Tools",
    tools1Desc: "Next.js, Tailwind CSS, Framer Motion",
    complete1: "Completion Timeline",
    complete1Desc: "3 Days",
    started: "How It All Began",
    startedDesc:
      "I began building this modern SaaS platform to simplify business operations by leveraging Next.js for its powerful server-side rendering and routing capabilities. To create a seamless and visually appealing interface, I used Framer Motion for smooth animations and Tailwind CSS for rapid, responsive styling. The development process involved structuring reusable components, implementing interactive transitions, and ensuring a user-friendly experience. This project allowed me to enhance my skills in modern front-end frameworks and deliver a polished application.",
    process: "Project Process",
    processDesc:
      "This SaaS platform began with planning and research to define its goal: simplifying business operations through user-friendly tools. After studying similar platforms, I outlined the structure with wireframes. Using Next.js for fast performance, Framer Motion for dynamic animations, and Tailwind CSS for responsive designs, I developed an intuitive and visually appealing interface. The process included rigorous testing for compatibility and continuous refinement based on feedback, ensuring a seamless and accessible user experience.",
    github: "https://github.com/SabaGG71/saiberNext",
    alt: "SaiberNext",
  },
  {
    id: "3",
    image: "/medico.jpg",
    imageDetailed: "/medicoDetailed.png",
    title: "Medico - Dental Clinic",
    detailedtitle: "💉 Medico - Dental Clinic",
    description:
      "A dental clinic providing expert care with advanced treatments in a patient-friendly environment.",
    link: "https://dental-clinic-medico.vercel.app/",
    Detaileddescription:
      "A leading dental clinic offering expert care with cutting-edge treatments in a comfortable and patient-friendly environment. Our clinic is equipped with the latest technology to ensure that every patient receives the highest standard of dental care. From routine check-ups and cleanings to advanced procedures like orthodontics, implants, and cosmetic dentistry, we prioritize your health and well-being.",
    industry1: "Industry",
    industryDesc1: "Dental Clinic",
    service1: "Service",
    serviceDesc1: "Dental Care Services",
    tools1: "Tools",
    tools1Desc: "Next.js, CSS, Responsive Design",
    complete1: "Completion Timeline",
    complete1Desc: "2 Weeks",
    started: "How It All Began",
    startedDesc:
      "The creation of this dental clinic website started with a vision to showcase expert care and advanced treatments in a welcoming and patient-friendly environment. Leveraging Next.js for its dynamic capabilities and CSS for styling, I ensured a sleek, responsive design. To enhance the user experience, I incorporated smooth animations that add a professional and engaging touch, making navigation seamless and visually captivating.",
    process: "Project Process",
    processDesc:
      "The idea started with a vision to create a website that reflects the clinic's dedication to patient care. Using Next.js, I prioritized performance and responsiveness. CSS was employed to craft a clean, modern layout, while animations were integrated to enhance user engagement and create smooth interactions.",
    github: "https://github.com/SabaGG71/clinic-website",
    alt: "Medico",
  },
  {
    id: "4",
    image: "/project4.jpg",
    imageDetailed: "/project4Detailed.png",
    title: "Worldwise - Travel Tracking",
    detailedtitle: "🟢 Worldwise - Travel Tracking",
    description:
      "An app that lets you track your travels, document destinations, and relive your journeys with ease.",
    link: "https://worldwiseofficial.netlify.app/",
    Detaileddescription:
      "An innovative travel app designed to help you track, document, and relive your journeys with ease. With this app, you can capture every destination you visit, making it simple to record key details such as locations, experiences, photos, and notes. Whether you're on a weekend getaway or an international adventure, the app allows you to log your travels in real-time. Users can create custom itineraries, track routes on interactive maps, and keep a visual timeline of their trips.",
    industry1: "Industry",
    industryDesc1: "Travel",
    service1: "Service",
    serviceDesc1: "Travel Tracker",
    tools1: "Tools",
    tools1Desc: "React, CSS, Leaflet",
    complete1: "Completion Timeline",
    complete1Desc: "1 Week",
    started: "How It All Began",
    startedDesc:
      "I embarked on building this travel tracker app to help users document and track their journeys seamlessly. Using React.js for its flexibility and dynamic capabilities, I focused on creating an engaging user experience. I integrated CSS for styling and Leaflet to display interactive maps for easy location tracking. The goal was to provide a simple yet powerful platform that helps users capture their travel experiences and explore new destinations with ease.",
    process: "Project Process",
    processDesc:
      "The development of the ✈️ travel tracker app began with creating a clear user flow to ensure ease of use. I focused on integrating React.js for efficient state management and dynamic content rendering. For the mapping functionality, I incorporated Leaflet to provide interactive and responsive maps, allowing users to track their destinations effortlessly. The app was styled 💅 with CSS to maintain a clean, modern look, and I optimized the layout for a smooth user experience across devices. Throughout the process, I tested and refined the features, focusing on usability and performance, ensuring the app meets the needs of travelers.",
    github: "https://github.com/SabaGG71/wordwiseApp",
    alt: "Worldwise",
    note: "* Not Responsive",
  },
  {
    id: "5",
    image: "/fitfactory.jpg",
    imageDetailed: "/fitfactoryDetailed.png",
    title: "Fitfactory - Gym Website",
    detailedtitle: "💪 Fitfactory - Gym Website",
    Detaileddescription:
      "An innovative travel app that helps you track, document, and relive your journeys. Easily capture details of each destination, including locations, experiences, photos, and notes. Whether it's a weekend getaway or an international trip, the app lets you log your travels in real-time. Create custom itineraries, track routes on interactive maps, and view a visual timeline of your adventures.",
    description:
      "Achieve your fitness goals with modern equipment, expert trainers, and a supportive community.",
    link: "https://thriving-squirrel-423dee.netlify.app/",
    industry1: "Industry",
    industryDesc1: "fitness",
    service1: "Service",
    serviceDesc1: "wellness",
    tools1: "Tools",
    tools1Desc: "React, CSS, Responsive Design",
    complete1: "Completion Timeline",
    complete1Desc: "3 Weeks",
    started: "How It All Began",
    startedDesc:
      "The fitness website project began with the goal of creating an intuitive platform for users to track their fitness journey. I started by using React.js to build the user interface, allowing for dynamic content and seamless interactions. CSS was utilized to design a clean, responsive layout that adapts well to different devices. The focus was on delivering a user-friendly experience, with features such as progress tracking and community engagement. The app was built to motivate users by offering easy access to workout plans, trainer guidance, and fitness resources.",
    process: "Project Process",
    processDesc:
      "For the FitFactory project, I set out to create a comprehensive fitness website that allows users to reserve gym trainers and book sessions based on their preferred times. I started by designing the core features, including a booking system that allows users to choose from a range of trainers, view their availability, and schedule sessions. I used React.js for building a dynamic and user-friendly interface, ensuring the website was responsive and easy to navigate. CSS was utilized to create a modern, clean design, focusing on ease of use and a seamless experience for users. After the initial development, I conducted thorough testing to ensure that the booking system worked smoothly across devices. The final product provides users with the flexibility to schedule personalized training sessions, ensuring they get the most out of their fitness journey.",
    github: "https://github.com/SabaGG71/fitfactory",
    alt: "Fitfactory",
  },
  {
    id: "6",
    imageDetailed: "/quizApp.png",
    image: "/quiz.jpg",
    detailedtitle: "➗ Quiz - React Quiz",
    title: "Quiz - React Quiz",
    description:
      "Challenge yourself with interactive quizzes, track your progress, and boost your knowledge with our React-powered Quiz App!",
    link: "https://quizreactapplication.netlify.app/",
    Detaileddescription:
      "Our React-powered Quiz App offers an engaging platform to challenge yourself with a variety of interactive quizzes. Whether you're testing your knowledge on general topics or diving deep into specific subjects, the app provides an array of quizzes to suit your interests. Track your progress as you complete each quiz, view detailed performance results, and identify areas to improve. With a user-friendly interface and real-time feedback, you can boost your knowledge and enjoy learning at your own pace. Challenge friends or compete with other users to make learning even more fun!",
    industry1: "Industry",
    industryDesc1: "Education",
    service1: "Service",
    serviceDesc1: "Interactive Learning",
    tools1: "Tools",
    tools1Desc: "React, CSS, Responsive Design",
    complete1: "Completion Timeline",
    complete1Desc: "4 Days",
    started: "How It All Began",
    startedDesc:
      "The Quiz App was created to offer an interactive learning experience. I chose React for its flexibility and CSS for a clean, user-friendly design. To manage the app's state, I used useReducer, which helped handle features like scoring and question navigation. My goal was to build a fun and engaging app that allows users to test and improve their knowledge.",
    process: "Project Process",
    processDesc:
      "The development of the Quiz App started with creating a clean and simple UI, focusing on making it intuitive for users. I designed a question and answer flow, ensuring smooth navigation between questions. Using React components, I structured the app to allow easy updates and maintainability. useReducer was essential for managing the state, such as tracking scores and question progress. I then implemented timers and animations to add an interactive touch. Throughout the process, I focused on optimizing performance and creating a responsive design to ensure the app works seamlessly on all devices.",
    github: "https://github.com/SabaGG71/quizApp",
    alt: "React Quiz",
  },
];
